name: Test Action

# until this action support more than just PRs, it can't be tested without a PR
on:
  pull_request:

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          paths: 'test/*'
          github-token: ${{ github.token }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
